table Geography
	lineageTag: f0c7fb45-4c99-40a6-beb8-a6ffc978072b

	column 'Geography Key'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 64ead67c-9d8e-44ad-9add-fdfff1680d26
		summarizeBy: none
		sourceColumn: Geography Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 07bdc493-96a4-4785-b2c1-d6fdd7c06a1d
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column StateProvinceCode
		dataType: string
		isHidden
		lineageTag: df440d6b-8c56-4046-8628-3769d863f1bc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: StateProvinceCode

		changedProperty = DataCategory

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'State Province'
		dataType: string
		lineageTag: f8318920-e70f-4089-ae4f-185b522dbfb5
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State Province

		changedProperty = DataCategory

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 1644185b-4b1e-4cc0-b722-c64fa2080fc5
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 6bf4b32f-a194-49bd-be79-83b18009a0e7
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Geography-a46e4687-1587-4fe6-a284-382852dd68e4 = m
		mode: import
		source =
				let
				    Source = Web.BrowserContents("https://guyinacube.com/geography-sample/"),
				    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7)"}, {"Column2", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6)"}, {"Column3", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5)"}, {"Column4", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4)"}, {"Column5", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3)"}, {"Column6", "TABLE > * > TR > TH[colspan=""6""]:not([rowspan]):nth-child(1):nth-last-child(1), TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2)"}, {"Column7", "TABLE > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(1), TABLE > * > TR > TD:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(1)"}}, [RowSelector="TABLE > * > TR"]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Table From Html",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Geography Key", Int64.Type}, {"City", type text}, {"StateProvinceCode", type text}, {"StateProvinceCodeName", type text}, {"CountryRegionName", type text}, {"PostalCode", type text}, {"SalesTerritoryKey", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"SalesTerritoryKey"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"CountryRegionName", "Country"}, {"PostalCode", "Postal Code"}, {"StateProvinceCodeName", "State Province"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

